# Generated by Django 5.1.1 on 2024-10-11 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_category_discount_remove_category_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='./static/media/author')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descript', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_exist', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='creatAt',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='descript',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='updateAt',
        ),
        migrations.AddField(
            model_name='category',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='isExist',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/media/category'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descript', models.TextField()),
                ('price', models.FloatField()),
                ('discountPer', models.FloatField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='./static/media/book')),
                ('creatAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isExist', models.BooleanField(default=True)),
                ('isOutStanding', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('idAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descript', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./static/media/blog')),
                ('creatAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isExist', models.BooleanField(default=True)),
                ('isOutStanding', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('blogCate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs_from_blogCate', to='api.categoryblog')),
                ('categoryBlogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs_from_categoryBlogID', to='api.categoryblog')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt', models.TextField()),
                ('idBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
