# Generated by Django 5.1 on 2024-10-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_author_categoryblog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creatAt',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='creatAt',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='creatAt',
            new_name='createAt',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='isExist',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='isOutStanding',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isExist',
        ),
        migrations.RemoveField(
            model_name='category',
            name='isExist',
        ),
        migrations.RemoveField(
            model_name='categoryblog',
            name='is_exist',
        ),
    ]
