# Generated by Django 5.1 on 2024-10-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_book_price_alter_book_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='idAuthor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='categoryID',
            new_name='Category',
        ),
    ]
